### ISSUE TITLE
error on Songs and Artist menu

### ISSUE THREAD

**Issue by FernetMenta** [spacys/mediathek#67]
I tried the Matrix version of this addon. When I try to open the Songs or Artists menu I get this error:

```
2021-02-28 14:50:17.463 T:11666   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: can only concatenate str (not "bytes") to str
                                                   Traceback (most recent call last):
                                                     File "/home/xbmc/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 1041, in <module>
                                                       AmazonMedia().reqDispatch()
                                                     File "/home/xbmc/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 84, in reqDispatch
                                                       self.createList(self.AMm.menuSongs(),True)
                                                     File "/home/xbmc/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 195, in createList
                                                       title += self.AMs.getSetting(item['search']).encode("UTF-8")
                                                   TypeError: can only concatenate str (not "bytes") to str
                                                   -->End of Python script error report<--
                                                   
2021-02-28 14:50:17.464 T:11666   DEBUG <general>: onExecutionDone(5, /home/xbmc/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py)
2021-02-28 14:50:17.483 T:11564   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-02-28 14:50:17.483 T:11564   DEBUG <general>: Window DialogNotification.xml was already loaded
2021-02-28 14:50:17.483 T:11564   DEBUG <general>: Alloc resources: 0.00ms
2021-02-28 14:50:17.484 T:11666   DEBUG <general>: .
2021-02-28 14:50:17.533 T:11666    INFO <general>: Python interpreter stopped
2021-02-28 14:50:17.533 T:11666   DEBUG <general>: Thread LanguageInvoker 140734518777408 terminating
2021-02-28 14:50:17.549 T:11665   ERROR <general>: GetDirectory - Error getting plugin://plugin.audio.amazonmedia/?mode=menuSongs
```

**Comment by spacys** [comment]
I can reproduce this issue, will check it. Thanks for the hint.

**Comment by spacys** [comment]
Please check with the new version 1.0.3

**Comment by FernetMenta** [comment]
That was fast. Thanks, I will try tomorrow and report back.

**Comment by FernetMenta** [comment]
Works. Thank you!
