### ISSUE TITLE
Plugin fails on Libreelec RPi3

### ISSUE THREAD

**Issue by FernetMenta** [spacys/mediathek#70]
I installed the plugin on a Raspberry Pi running Libreelec 10 (Matrix). Python 3.8.7

I can navigate the menu but as soon any songs should appear on the list I get this kind of error

```
2021-03-02 12:04:58.006 T:885      INFO <general>: CPythonInvoker(2, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): script successfully run
2021-03-02 12:04:58.458 T:885      INFO <general>: Python interpreter stopped
2021-03-02 12:05:00.321 T:888      INFO <general>: initializing python engine.
2021-03-02 12:05:02.856 T:888      INFO <general>: CPythonInvoker(3, /storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py): script successfully run
2021-03-02 12:05:03.315 T:888      INFO <general>: Python interpreter stopped
2021-03-02 12:05:04.588 T:891      INFO <general>: initializing python engine.
2021-03-02 12:05:07.167 T:891     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'playlists'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 1041, in <module>
                                                       AmazonMedia().reqDispatch()
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 134, in reqDispatch
                                                       self.getOwnedPlaylists()
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 249, in getOwnedPlaylists
                                                       self.setAddonContent('ownedplaylists',items,'albums')
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 671, in setAddonContent
                                                       for item in param['playlists']:
                                                   KeyError: 'playlists'
                                                   -->End of Python script error report<--
                                                   
2021-03-02 12:05:07.626 T:891      INFO <general>: Python interpreter stopped
2021-03-02 12:05:07.642 T:890     ERROR <general>: GetDirectory - Error getting plugin://plugin.audio.amazonmedia/?mode=getOwnedPlaylists

```

**Comment by FernetMenta** [comment]
I resetted the addon, entered my credentials again. Then it worked. Seems I was not authenticated and the addon didn't notice.
