### ISSUE TITLE
Unable to load any songs/artists/radios/etc

### ISSUE THREAD

**Issue by SerialVelocity** [spacys/mediathek#92]
Hey,

I'm unable to load anything right now. It says there's an error. I've attached the error from the logs.

Region: UK
Device: Nvidia Shield
Kodi version: 19.3
Plugin version: 1.1.0

Error:
```
2022-03-04 00:58:49.879 T:31171   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'results'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 713, in <module>
                                                       AmazonMedia().reqDispatch()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 81, in reqDispatch
                                                       elif mode == 'searchArtist':    self.searchItems(['artists','catalog_artist'],30014)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 280, in searchItems
                                                       items = resp['results'][0]
                                                   KeyError: 'results'
                                                   -->End of Python script error report<--
```

**Comment by spacys** [comment]
Hi,
`keyError` has normally something to do with invalid credentials. Please go to the Addon Settings and click on `Reset Credentials`. Afterwards the Addon ask for `user` and `password` and it should work again.
If this was the solution, please give me a hint, then I will check how to cover such issues in the future.

**Comment by spacys** [comment]
The settings was not working as expected...a new version is now available, please try again.

**Comment by spacys** [comment]
Do you have any feedback for me?

**Comment by RosensRauk** [comment]
1.Input credentials does not save. All interaction asked me to input credentials. 
2.Can't play anything!
3. When doing a search (after I input credentials) nothing happens.
4. Trying from Yatse and directly from vim3

coreELEC 19.4 (fresh install)
Vim3 Pro

The app works in Sweden(geo)

I'm new at test feedback so let me know how, and il help you the best I can
Fritz/Sweden

**Comment by SerialVelocity** [comment]
hi @spacys , I haven't tested this again yet. I'll try to get to it soon.
