### ISSUE TITLE
not working in France

### ISSUE THREAD

**Issue by dfrey** [spacys/mediathek#99]
Hi, 
thanks for this software. I just tested it on my raspberry py and the login process does not work. Essentially, your code expects a page with two input boxes, one for username and another for password. The current Amazon login page in France displays first a page asking for the username and only later does it show a page asking for a password. 
Any chance you can fix this? Otherwise I can give it a shot when I have some spare time.

**Comment by spacys** [comment]
Behind this "two" logon pages is still the same form, so it should work. Do you see any error messages?

**Comment by spacys** [comment]
is it working now?

**Comment by edheldil** [comment]
I have the same issue, as far as I can tell. I start the plugin, enter my username and password and the plugin reports some error and I have to input my username / password again next time I run the plugin. The error message refers to log, but that does not contain anything relevant.

I use kodi on raspberry pi with LibreElec, amazon.co.uk account from Czech Republic.

**Comment by edheldil** [comment]
Did amazon change their login pages?

```
2023-03-01 23:32:37.835 T:4868    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>
                                                   Error Contents: HTTP Error 404: Not Found
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 43, in reqDispatch
                                                       self.credentials = self.load()
                                                                          ^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/resources/lib/tools.py", line 135, in load
                                                       with open(oPath, 'rb') as file:
                                                            ^^^^^^^^^^^^^^^^^
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/storage/.kodi/userdata/addon_data/plugin.audio.amazonmedia/data.obj'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 718, in <module>
                                                       AmazonMedia().reqDispatch()
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/amazonmedia.py", line 45, in reqDispatch
                                                       self.credentials = AMlogon().amazonLogon()
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.amazonmedia/resources/lib/logon.py", line 72, in amazonLogon
                                                       self._br.open(amzURL)
                                                     File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 253, in open
                                                       return self._mech_open(url_or_request, data, timeout=timeout)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 309, in _mech_open
                                                       raise response
                                                   mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 404: Not Found
                                                   -->End of Python script error report<--
```

**Comment by edheldil** [comment]
Perhaps this is relevant, as the login process in browser uses `/ap/signin` as well.
https://stackoverflow.com/questions/54622367/how-to-login-to-audible-com-subsidiary-of-amazon-using-python

**Comment by spacys** [comment]
So you have a Czech Republic account? Which Amazon Domain was used...was it `amazon.co.uk`? Is this a valid combination?

**Comment by ulhu** [comment]
Hello,
I have the same issue. I use a German Account with the German Domain.

**Comment by gd71** [comment]
Hello,
got it working successfully from France by using this url in amazonLogon function in logon.py 
`        amzURL = 'https://music.amazon.{}/forceSignIn?useHorizonte=true'.format(self.credentials.USERTLD) 
` 
rest of the code in untouched
Not tested for other countries
